moviesproject/moviesapp/urls.py
from django.urls import path
from  .import views
app_name='moviesapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movies/<int:movies_id>/',views.detail,name='detail'),
    path('add/',views.add_movies,name='add_movies'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')

]

moviesproject/moviesproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("moviesapp.urls"))
]
if settings.DEBUG:
    urlpatterns  += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moviesproject/moviesapp/models.py
from django.db import models

# Create your models here.
class Movies(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

moviesproject/moviesapp/forms.py
from  django import  forms
from .models import Movies

class MoviesForm(forms.ModelForm):
    class Meta:
        model=Movies
        fields = ['name','desc','year','img']

moviesproject/moviesapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from  .models import Movies
from .forms import MoviesForm

# Create your views here.
def index(request):
    movies=Movies.objects.all()
    context={
        'movies_list':movies
    }
    return   render(request,'index.html',context)
def detail(request,movies_id):
    movies=Movies.objects.get(id=movies_id)
    return   render(request,"detail.html",{'movies':movies})

def add_movies(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        img = request.FILES['img']
        movies=Movies(name=name,desc=desc,year=year,img=img)
        movies.save()

    return  render(request,'add.html')

def update(request,id):
    movies=Movies.objects.get(id=id)
    form=MoviesForm(request.POST or None, request.FILES,instance=movies)
    if form.is_valid():
        form.save()
        return  redirect('/')
    return  render(request,'edit.html',{'form':form,'movies':movies})

def delete(request,id):
    if request.method=='POST':
        movies=Movies.objects.get(id=id)
        movies.delete()
        return  redirect('/')
    return  render(request,'delete.html')

moviesproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <input type="text" name="name"  placeholder="Enter your movie name">
        <input type="text" name="desc"  placeholder="Enter your movie description">
        <input type="text" name="year"  placeholder="Enter your movie year">
        <input type="file" name="img">
        <input type="submit">


</form>
{% endblock %}

moviesproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    online Movies store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

moviesproject/templates/delete.html
<form method="POST">

  {% csrf_token %}
  Are you want to delete the movie?
  <input type="submit">
</form>

moviesproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
           <img src="{{movies.img.url}}"  height="250">
        </div>
<div class="col-md-6">
    <h2>{{movies.name}}</h2>
    <h4>{{movies.desc}}</h4>
    <h6>{{movies.year}}</h6>
    <a class="btn btn-warning" href="{% url 'moviesapp:update' movies.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'moviesapp:delete' movies.id %}">Delete</a>

</div>
    </div>
</div>

{% endblock %}

moviesproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

moviesproject/templates/index.html
{% extends 'base.html' %}
{% block body %}



<div class="container">
    <div class=" row">
        {% for i in movies_list %}
        <div class="col-md-3">
            <div class="card" >
                 <img src="{{i.img.url}}"  class="card-img-top" alt="..."   height="250;">
                 <div class="card-body">
                     <h5 class="card-title">{{i.name}}</h5>
                     <p class="card-text">{{i.price}}</p>
                     <a href="{%  url 'moviesapp:detail' i.id %}" class="btn btn-primary">view details</a>
                 </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}